<?php

// Starter website content, loaded into the database by ContentSeeder (php artisan db:seed).
// After seeding, manage this content in the admin panel (/admin).

return [
    [
        'slug' => 'best-time-for-a-tanzania-safari',
        'title' => 'When Is the Best Time for a Tanzania Safari?',
        'category' => 'safari',
        'date' => '2026-09-18',
        'read_minutes' => 5,
        'image' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'Dry season, green season, calving and river crossings: how the time of year shapes what you will see on safari.',
        'body' => [
            'There is no single best month for a Tanzania safari. Each season offers something different, so the right time depends on what you most want to see and how you like to travel.',
            '## The dry season (June to October)',
            'The long dry season is the most popular time to visit. Vegetation thins out and animals gather around rivers and waterholes, which makes wildlife easier to find. Days are sunny and mornings can be surprisingly cold, so pack a warm layer.',
            '## The green season (November to May)',
            'After the short rains the landscapes turn green, prices are often lower and the parks are quieter. Early in the year, the wildebeest herds gather in the southern Serengeti for the calving season, which also attracts predators.',
            '## The long rains (April and May)',
            'April and May bring the heaviest rains. Some camps close and a few roads become harder to drive, but you can enjoy dramatic skies, lush scenery and the parks almost to yourself.',
            'Not sure which season suits you? Tell us what you would love to see and we will suggest the right timing and route.',
        ],
    ],
    [
        'slug' => 'what-to-pack-for-your-first-safari',
        'title' => 'What to Pack for Your First Safari',
        'category' => 'travel-tips',
        'date' => '2026-08-30',
        'read_minutes' => 4,
        'image' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'Neutral layers, good binoculars and a soft bag: a simple packing list for comfortable days on game drives.',
        'body' => [
            'Packing for a safari is simpler than many people expect. Comfortable, practical clothing and a few key items will cover almost everything.',
            '## Clothing',
            'Choose neutral colours such as khaki, olive and beige, and dress in layers. Early mornings and evenings can be cool, while midday is warm. A light fleece, a wide-brimmed hat and comfortable closed shoes are essentials.',
            '## Gear',
            'Bring binoculars (one pair per person if you can), sunglasses, sunscreen, insect repellent and a power bank. A camera with a zoom lens helps, but a good phone camera is fine for most travellers.',
            '## Bags',
            'Soft duffel bags fit safari vehicles and light aircraft far better than hard suitcases. If your trip includes internal flights, check the airline\'s luggage weight limit before you pack.',
        ],
    ],
    [
        'slug' => 'machame-vs-lemosho-kilimanjaro-route',
        'title' => 'Machame vs Lemosho: Choosing Your Kilimanjaro Route',
        'category' => 'climbing',
        'date' => '2026-08-12',
        'read_minutes' => 6,
        'image' => 'https://images.unsplash.com/photo-1621414050946-1b936a78491f?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'Two of the most popular ways to the summit compared: scenery, crowds, number of days and acclimatisation.',
        'body' => [
            'Machame and Lemosho are two of the most popular routes up Kilimanjaro, Africa\'s highest mountain at 5,895 metres. Both are beautiful; the right choice depends on your time, budget and how you handle altitude.',
            '## Machame',
            'Often called the "Whiskey Route", Machame is usually climbed over six or seven days. It passes through rainforest, moorland and alpine desert, and follows a "climb high, sleep low" profile that supports acclimatisation. It is busier than some other routes.',
            '## Lemosho',
            'Lemosho approaches from the west and crosses the wide Shira Plateau. It is typically climbed over seven or eight days, is quieter in its early stages, and the extra time helps your body adjust to the altitude.',
            '## Which should you choose?',
            'More days on the mountain generally means better acclimatisation and a more enjoyable climb. If your schedule allows, a longer itinerary is usually worth it. We are happy to help you compare options for your dates.',
        ],
    ],
    [
        'slug' => 'understanding-the-great-migration',
        'title' => 'Understanding the Great Migration',
        'category' => 'safari',
        'date' => '2026-07-21',
        'read_minutes' => 5,
        'image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'Where the herds are through the year, and how to plan your safari around one of nature\'s great journeys.',
        'body' => [
            'Every year, well over a million wildebeest, along with large numbers of zebra and gazelle, move in a great loop through the Serengeti ecosystem in search of fresh grazing.',
            '## A year on the move',
            'Early in the year the herds gather on the short-grass plains of the southern Serengeti, where most calves are born. As the land dries out they move west and north, and in the middle of the year they reach the northern Serengeti, where the famous river crossings take place.',
            '## Timing is never exact',
            'The migration follows the rains, not the calendar, so the herds can arrive earlier or later than expected. A flexible itinerary and an experienced guide give you the best chance of being in the right place.',
        ],
    ],
    [
        'slug' => 'tanzania-travel-essentials',
        'title' => 'Tanzania Travel Essentials: Visas, Health and Money',
        'category' => 'travel-tips',
        'date' => '2026-06-28',
        'read_minutes' => 5,
        'image' => 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'The practical things to sort out before you fly, from entry requirements to vaccinations and payments.',
        'body' => [
            'A little preparation makes arriving in Tanzania smooth and stress-free. Entry and health rules can change, so always confirm the latest requirements with official sources before you travel.',
            '## Visas',
            'Most visitors need a visa to enter Tanzania. Many nationalities can apply online in advance through the official government e-visa service, which saves time on arrival.',
            '## Health',
            'Speak with a travel health clinic well before your trip about recommended vaccinations and malaria prevention. A yellow fever certificate may be required depending on the countries you travel through.',
            '## Money',
            'The local currency is the Tanzanian shilling. US dollars are widely used for tourism services, and cards are accepted in many hotels and lodges, though it is useful to carry some cash for tips and small purchases.',
        ],
    ],
    [
        'slug' => 'adding-zanzibar-after-your-safari',
        'title' => 'Adding Zanzibar After Your Safari',
        'category' => 'travel-tips',
        'date' => '2026-06-05',
        'read_minutes' => 3,
        'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=75',
        'excerpt' => 'How many beach days to plan, which coast to choose and the experiences worth leaving the sun lounger for.',
        'body' => [
            'After early mornings and dusty game drives, a few days on Zanzibar is the perfect way to unwind before flying home.',
            '## How long to stay',
            'Three to five nights is a good balance for most travellers: enough time to relax on the beach and still explore Stone Town and the island\'s spice farms.',
            '## What to do',
            'Wander the historic alleys of Stone Town, visit a spice farm, sail on a traditional dhow at sunset or go snorkelling on the reefs. Or simply do nothing at all.',
        ],
    ],
];
