<?php

// Starter website content, loaded into the database by ContentSeeder (php artisan db:seed).
// After seeding, manage this content in the admin panel (/admin).

return [
    [
        'slug' => 'serengeti-ngorongoro-safari',
        'featured' => true,
        'types' => ['migration'],
        'category' => 'Safari',
        'tagline' => 'The classic northern circuit',
        'title' => 'Serengeti & Ngorongoro Safari',
        'chips' => [
            ['label' => '5 Days'],
            ['label' => 'Classic'],
            ['label' => 'Big Five', 'highlight' => true],
        ],
        'text' => 'Endless plains, big cats and a full day on the crater floor, with time to follow the herds at their own pace.',
        'price' => 1650,
        'image' => 'https://images.unsplash.com/photo-1535941339077-2dd1c7963098?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'machame-route',
        'featured' => true,
        'types' => ['kilimanjaro'],
        'category' => 'Kilimanjaro',
        'tagline' => 'The classic whiskey route',
        'title' => 'Machame Route',
        'chips' => [
            ['label' => '7 Days'],
            ['label' => 'Challenging'],
            ['label' => 'Rainforest to glacier', 'highlight' => true],
        ],
        'text' => 'Kilimanjaro\'s most popular route, with varied scenery and a gradual climb that helps you acclimatise.',
        'price' => 1950,
        'image' => 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'zanzibar-beach-escape',
        'featured' => true,
        'types' => ['zanzibar'],
        'category' => 'Zanzibar',
        'tagline' => 'Stone Town & shores',
        'title' => 'Zanzibar Beach Escape',
        'chips' => [
            ['label' => '4 Days'],
            ['label' => 'Relaxed'],
            ['label' => 'Beach & culture', 'highlight' => true],
        ],
        'text' => 'Explore Stone Town\'s history and spice markets, then unwind on white-sand beaches by the Indian Ocean.',
        'price' => 650,
        'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'safari-and-sea-honeymoon',
        'types' => ['honeymoon', 'luxury', 'zanzibar'],
        'category' => 'Honeymoon',
        'tagline' => 'Savannah sunsets, island nights',
        'title' => 'Safari & Sea Honeymoon',
        'chips' => [
            ['label' => '9 Days'],
            ['label' => 'Romantic'],
            ['label' => 'Private guide', 'highlight' => true],
        ],
        'text' => 'Intimate tented camps in the Serengeti and Ngorongoro, followed by slow beach days on Zanzibar.',
        'price' => null,
        'image' => 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'family-safari-adventure',
        'types' => ['family'],
        'category' => 'Family',
        'tagline' => 'Shorter drives, bigger smiles',
        'title' => 'Family Safari Adventure',
        'chips' => [
            ['label' => '6 Days'],
            ['label' => 'Easy pace'],
            ['label' => 'All ages', 'highlight' => true],
        ],
        'text' => 'Tarangire\'s elephants, the Ngorongoro Crater and family-friendly lodges with pools and space to play.',
        'price' => null,
        'image' => 'https://images.unsplash.com/photo-1585970480901-90d6bb2a48b5?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'fly-in-serengeti-luxury',
        'types' => ['luxury'],
        'category' => 'Luxury',
        'tagline' => 'Skip the long roads',
        'title' => 'Fly-in Serengeti Luxury',
        'chips' => [
            ['label' => '5 Days'],
            ['label' => 'Exclusive'],
            ['label' => 'Fly-in', 'highlight' => true],
        ],
        'text' => 'Light-aircraft hops between the parks, top lodges and private game drives timed to the best light.',
        'price' => null,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'great-migration-river-crossings',
        'types' => ['migration'],
        'category' => 'Migration',
        'tagline' => 'Front row at the Mara River',
        'title' => 'Great Migration River Crossings',
        'chips' => [
            ['label' => '7 Days'],
            ['label' => 'Seasonal'],
            ['label' => 'Jul – Oct', 'highlight' => true],
        ],
        'text' => 'Camp close to the herds in the northern Serengeti for the best chance of seeing a dramatic river crossing.',
        'price' => null,
        'image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=900&q=75',
    ],
    [
        'slug' => 'lemosho-route',
        'types' => ['kilimanjaro'],
        'category' => 'Kilimanjaro',
        'tagline' => 'The scenic western approach',
        'title' => 'Lemosho Route',
        'chips' => [
            ['label' => '8 Days'],
            ['label' => 'Challenging'],
            ['label' => 'Quieter trails', 'highlight' => true],
        ],
        'text' => 'A longer, quieter route across the Shira Plateau, with extra days that give your body more time to adjust.',
        'price' => null,
        'image' => 'https://images.unsplash.com/photo-1621414050946-1b936a78491f?auto=format&fit=crop&w=900&q=75',
    ],
];
