<?php

/*
|--------------------------------------------------------------------------
| Quotations (PDF)
|--------------------------------------------------------------------------
|
| Company details printed on quotes come from config/site.php (.env SITE_*).
|
*/

return [

    'currency_symbol' => env('QUOTE_CURRENCY_SYMBOL', '$'),

    // How long a quote is valid, in days.
    'validity_days' => (int) env('QUOTE_VALIDITY_DAYS', 30),

    // Instant quotes on package pages: children's price as a % of the adult price.
    'child_rate_percent' => (int) env('QUOTE_CHILD_RATE_PERCENT', 100),

    // Printed under the totals on every quote.
    'terms' => [
        'Prices are per the itemised costs above and quoted in US dollars.',
        'The quote is valid until the date shown and subject to availability at the time of booking.',
        'International flights, visas, travel insurance and personal expenses are not included unless listed.',
        'Your booking is confirmed once we have received your deposit and sent written confirmation.',
    ],

    // Shown on instant quotes generated by visitors.
    'instant_note' => 'This is an instant estimate based on our standard package price. The final price depends on travel dates, accommodation choices and availability; our team will confirm everything with you by email.',

];
