<?php

namespace App\Http\Controllers;

use App\Filament\Resources\Quotes\QuoteResource;
use App\Mail\InstantQuoteCreated;
use App\Models\Package;
use App\Models\Quote;
use App\Support\AdminAlerts;
use App\Support\QuotePdf;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\URL;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

/**
 * Instant quotes generated by visitors on a package page.
 */
class QuoteController extends Controller
{
    /** How long the visitor's download link keeps working. */
    protected const LINK_DAYS = 7;

    public function store(Request $request, string $slug): RedirectResponse
    {
        $package = Package::query()->published()->where('slug', $slug)->where('price', '>', 0)->firstOrFail();
        $back = route('safaris.show', $package->slug).'#instant-quote';

        // Honeypot: bots fill the hidden "website" field. Pretend nothing happened.
        if (filled($request->input('website'))) {
            return redirect()->to($back);
        }

        try {
            $data = $request->validateWithBag('quote', [
                'name' => ['required', 'string', 'max:120'],
                'email' => ['required', 'string', 'email:rfc', 'max:255'],
                'phone' => ['nullable', 'string', 'max:40'],
                'country' => ['nullable', 'string', 'max:80'],
                'travel_date' => ['required', 'date', 'after_or_equal:today'],
                'adults' => ['required', 'integer', 'min:1', 'max:30'],
                'children' => ['nullable', 'integer', 'min:0', 'max:30'],
            ], [
                'travel_date.after_or_equal' => 'Please choose a date from today onwards.',
            ]);
        } catch (ValidationException $e) {
            throw $e->redirectTo($back);
        }

        $adults = (int) $data['adults'];
        $children = (int) ($data['children'] ?? 0);
        $start = Carbon::parse($data['travel_date']);
        $days = count($package->itinerary ?? []); // one itinerary entry per day

        $quote = Quote::create([
            'source' => 'website',
            'status' => 'draft',
            'package_id' => $package->id,
            'customer_name' => $data['name'],
            'customer_email' => $data['email'],
            'customer_phone' => $data['phone'] ?? null,
            'customer_country' => $data['country'] ?? null,
            'adults' => $adults,
            'children' => $children,
            'travel_start' => $start,
            'travel_end' => $days > 1 ? $start->copy()->addDays($days - 1) : null,
            'items' => QuotePdf::packageItems($package, $adults, $children),
            'notes' => config('quotes.instant_note'),
            'valid_until' => now()->addDays(config('quotes.validity_days')),
        ])->refresh();

        if ($to = config('site.email')) {
            try {
                Mail::to($to)->send(new InstantQuoteCreated($quote));
            } catch (Throwable $e) {
                Log::error('Instant quote email failed', ['quote' => $quote->reference, 'error' => $e->getMessage()]);
            }
        }

        AdminAlerts::send(
            'New instant quote '.$quote->reference,
            $quote->customer_name.' · '.$package->title.' · '.Quote::money($quote->total),
            QuoteResource::getUrl('edit', ['record' => $quote], panel: 'admin'),
            'heroicon-o-document-currency-dollar',
        );

        return redirect()->to($back)->with('instant_quote', [
            'reference' => $quote->reference,
            'name' => $quote->customer_name,
            'url' => URL::temporarySignedRoute('quotes.pdf', now()->addDays(self::LINK_DAYS), ['quote' => $quote->id]),
        ]);
    }

    /**
     * Download a quote PDF through a signed link (handed to the visitor after they request it).
     */
    public function pdf(Quote $quote): Response
    {
        return response()->streamDownload(
            function () use ($quote) {
                echo QuotePdf::output($quote);
            },
            $quote->pdfFilename(),
            ['Content-Type' => 'application/pdf', 'X-Robots-Tag' => 'noindex'],
        );
    }
}
