<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A price quotation (created in the admin or generated by a visitor on a package page).
 * Items: [{description, quantity, unit_price}]. Totals are calculated, not stored.
 */
class Quote extends Model
{
    public const STATUSES = [
        'draft' => 'Draft',
        'sent' => 'Sent',
        'accepted' => 'Accepted',
        'declined' => 'Declined',
    ];

    protected $fillable = [
        'reference', 'source', 'status', 'package_id', 'trip_request_id',
        'customer_name', 'customer_email', 'customer_phone', 'customer_country',
        'adults', 'children', 'travel_start', 'travel_end', 'items', 'discount', 'notes', 'valid_until',
    ];

    protected $attributes = [
        'status' => 'draft',
        'source' => 'admin',
        'discount' => 0,
    ];

    protected function casts(): array
    {
        return [
            'items' => 'array',
            'discount' => 'decimal:2',
            'travel_start' => 'date',
            'travel_end' => 'date',
            'valid_until' => 'date',
        ];
    }

    /**
     * Reference like "QT-2026-000042", derived from the id once the quote exists.
     */
    protected static function booted(): void
    {
        static::created(function (Quote $quote) {
            if (! $quote->reference) {
                $quote->forceFill(['reference' => sprintf('QT-%s-%06d', $quote->created_at->format('Y'), $quote->id)])->saveQuietly();
            }
        });
    }

    public function package(): BelongsTo
    {
        return $this->belongsTo(Package::class);
    }

    public function tripRequest(): BelongsTo
    {
        return $this->belongsTo(TripRequest::class);
    }

    public static function lineTotal(array $item): float
    {
        return round((float) ($item['quantity'] ?? 0) * (float) ($item['unit_price'] ?? 0), 2);
    }

    protected function subtotal(): Attribute
    {
        return Attribute::get(fn () => round(collect($this->items ?? [])->sum(fn (array $item) => self::lineTotal($item)), 2));
    }

    protected function total(): Attribute
    {
        return Attribute::get(fn () => max(0, round($this->subtotal - (float) $this->discount, 2)));
    }

    public static function money(float|int|string|null $amount): string
    {
        return config('quotes.currency_symbol').number_format((float) $amount, 2);
    }

    public function pdfFilename(): string
    {
        return 'Quotation-'.($this->reference ?? 'draft').'.pdf';
    }
}
